### ISSUE TITLE
setting_hstore_extension variable isn't defined in ansible playbook

### ISSUE THREAD

**Issue by mwasilew** [Linaro/art-reports#26]
postrges hstore is only enabled when setting_hstore_extension is set to true:
https://github.com/Linaro/art-reports/blob/master/ansible/roles/postgres/tasks/main.yml#L42

However this variable isn't available in our playbook. Should we:
 a) remove the condition from postgres/tasks/main.yaml
 b) add variable to group_vars/all
?

**Comment by terceiro** [comment]
the hstore extension is a hard dependency now, so there is no point in using a boolean variable to control it.
