### ISSUE TITLE
500 error on calling benchmarks_compare

### ISSUE THREAD

**Issue by mwasilew** [Linaro/art-reports#3]
I'm getting the progress indicator only on accessing this URL:
https://art-reports.linaro.org/#/build/200

The logs show that https://art-reports.linaro.org/api/result/200/benchmarks_compare/ results in error 500. Details below:

    /srv/art-reports.linaro.org/.virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

AttributeError("'NoneType' object has no attribute 'measurement'",)

**Comment by terceiro** [comment]
I'm debugging this

**Comment by terceiro** [comment]
this is caused by a baseline build that had an incomplete job, so it does not have values for all benchmarks. I am writing a patch.

**Comment by mwasilew** [comment]
Fixed.
