### ISSUE TITLE
patched builds displayed in graphs

### ISSUE THREAD

**Issue by mwasilew** [Linaro/art-reports#4]
Only baseline build results should be displayed in graphs. When implementing 'click to see details' I noticed that some data points come from patched builds which shouldn't happen. Example picture enclosed. Clicking this point will take you to the patched build. 
URL: https://art-reports.linaro.org/#/stats/?branch=master&benchmark=MathPartialSums

![art_graphs](https://cloud.githubusercontent.com/assets/618901/13945530/fec408d4-f005-11e5-8694-af95fc5de48e.png)

**Comment by terceiro** [comment]
this has been fixed in f1d71a0ae86bf278ec092176b2214d4c5ea6413e , not sure with it's still open
